version: "3.3"

services:
  database:
    image: 'mariadb:10.10'
    container_name: 'database'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3305:3306"
    volumes:
      - "./docker/dbinit:/docker-entrypoint-initdb.d"